### PR TITLE
:SM (smallest magnitude) -> :SR (smallest real part)

### PR DESCRIPTION
**Pull request by frssp**
If V (and hence E) is negative, SM gives the eigenvalues close to zer…o first which is not what we expect.

:SM (smallest magnitude) -> :SR (smallest real part)
As long as V is Hermitian...

### CODE REVIEW

**Comment by RedPointyJackson** [comment]
@frssp You are right, nice catch. Why did you close the PR?

**Comment by frssp** [comment]
I found that :SM is more stable than :SR somehow. 

I encountered following error when I use :SR.

“””
Base.LinAlg.ARPACKException("unspecified ARPACK error: 1")
“”"

**Comment by RedPointyJackson** [comment]
That's [I think](https://stackoverflow.com/questions/40815467/in-julia-the-eigs-function-for-large-sparse-matrix-went-wrong), maximum number of iterations reached. Nevertheless, I still think that `:SM` it's incorrect and you are right on suggesting `:SR`, they are only equivalent when the matrix is small enough and all the eigenvalues are found.

**Comment by frssp** [comment]
Yes. That’s right. I also think :SR should be used.

And thank you for the nice program, Brooglie!

Best.

**Pull request closed without merging**
